### ISSUE TITLE
Polygon Files Importing as Multipolygon

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/dataservices-api#167]
@iriberri 

## Context
Importing shapefile or geojson of polygons is importing as multipolygons.

## Process
1) Export a polygon dataset from CartoDB as geojson or shapefile, import to CartoDB.
2) Will import as multipolygon even though previously stored as polygon data (tested with user's data), geojson file when viewed shows "polygon" feature collection, not multipolygons

Also tested with the US zcta census data downloaded from public site, which when viewed in QGIS, shows polygons (not multipolygons)
https://www.census.gov/geo/reference/zctas.html

## Expected Result
Should import and be stored as polygons

## Current Result
Import stored as multipolygons

**Comment by iriberri** [comment]
This issue should not actually live here, but in `cartodb/cartodb`.

Anyway, the result you are expecting is not the default one for CartoDB. It is purposely converting polygons (and lines) into multipolygons (or multilines), in order to make more homogeneous the support of multigeometries.

In the case of points, these should not be converted to multipoint because the Torque technology can't handle them, but otherwise, outside of this kind of map, it would not provoke any issue inside CartoDB.

Which is the real problem here? I'm assuming that there are some geospatial SQL queries involved that are making multipolygon handling a bit more complex than regular polygons, otherwise the behaviour of the multipolygon geometries is exactly the same as the polygon geometries (in terms of CartoCSS, rendering...).

**Comment by michellechandra** [comment]
hey @iriberri - the context for this issue is that a user had geometries stored as polygons in his account, we exported the data in order to test a SQL query, but the SQL query returned an error as was the query was expecting polygons not multipolygons. in the future, is there an extra step we should expect where we will need to convert multipolygons to polygons when applying SQL queries that expect polygons?

**Comment by iriberri** [comment]
You can change the geometry to be of type Polygon with a query using http://postgis.refractions.net/docs/ST_GeometryN.html, but import processes are always going to generate multipolygons. Perhaps the table he was using was old (not probable, I think geometries have been multipolygons for a looooong time or even always) or it was generated from a query (create table from query) that was creating polygons.

Closing, as there's no issue here. Feel free to drop me a line if you need!
