### ISSUE TITLE
Update return signatures for obs_getavailablegeometries and obs_getavailabletimespans

### ISSUE THREAD

**Issue by talos** [CartoDB/dataservices-api#361]
We need to update the DS wrappers for `obs_getavailablegeometries` and `obs_getavailabletimespans` to return several additional columns:

`OBS_GetAvailableGeometries`:

* `geom_type TEXT`
* `geom_extra JSONB`
* `geom_tags TEXT[]`

`OBS_GetAvailableTimespans`:

* `timespan_type TEXT`
* `timespan_extra JSONB`
* `timespan_tags TEXT[]`

Code should be addressed in #360, primarily excepting upgrade/downgrade paths.

Steps to get this deployed

1. Once the code in #360 is good, deploy updates to observatory-extension (this will temporarily break the two functions)
2. Merge and deploy #360 to client and server

**Comment by talos** [comment]
@rafatower @rochoa after some Jenkins hiccups last week, 1.5.0 is now successfully deployed on staging:

http://deploy.int.cartodb.net/view/Data%20Observatory/job/Deploy%20Observatory%20Extension/84/console

Feel free to kick it over to production when you'd like.  Since the two functions that break when dataservices-api is out of sync with observatory-extension aren't being used by anybody outside CARTO, the order (dataservices-api on prod then observatory or vice versa) shouldn't matter.

**Comment by rafatower** [comment]
@rochoa regarding upgrade/downgrade and versioning since we did peer programming I don't deem necessary a peer review, but just in case here's the diff:

https://github.com/CartoDB/dataservices-api/compare/master?expand=1

I'll deploy to staging and then wait for you to proceed with the rest.

**Comment by rafatower** [comment]
Done.

By the time I'm writing these lines, the server extension is updated and most of clients are as well.

You can test it with your team account.

Mind that the new columns are returned at the end rather than in the middle, as postgres `ALTER TYPE` does not allow for addition of new attributes in the middle of existing types. See https://www.postgresql.org/docs/9.5/static/sql-altertype.html

We've extensively tested that the different orders of the return fields do not pose trouble, as `pl/proxy` is able to handle that situation.

If the ordering of return fields is by any means an issue, please kindly update the observatory extension and documentation to keep it consistent.

If you were to modify any existing function, it is standard practice to add new params/return values at the end of existing ones. Please let's stick to that practice moving forward.

**Comment by talos** [comment]
Great! Works beautifully. Order should not matter.
