### ISSUE TITLE
Fix Mapbox Python tests

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/dataservices-api#457]
Currently, we are using a Mapbox access token from the Mapbox examples to execute the tests. It seems that they have recently disabled it and our tests are failing.

We don't want to create a CARTO owned access token for the tests because it will be public in our dataservices-api GitHub repo.

@ethervoid suggested that using Travis we can encrypt the config part and decrypt in Travis to use it in the tests (we can't use a configuration file generated with Chef for the tests)

**Comment by ethervoid** [comment]
Another option is what we're doing in the other services. For tests, except for end-to-end ones, we don't connect against a third-party service for multiple reasons (time to execute service, cost, api-keys, possible down of the service...). Instead of it, we gather multiple types of responses (success, empty, failed..) and we mock up them.

In case the API changes we should notice with the end-to-end tests

**Comment by juanignaciosl** [comment]
Ok, some questions...

1.- [dataservices-api is not configured in Travis](https://travis-ci.org/CartoDB/) but in [Jenkins](https://ci.cartodb.net/job/CartoDB-DATASERVICES-API-PR-testing). Do you see any value on moving it to Travis?
2.- How come we can't use Chef? 
3.- In staging we run the tests [with this command line](https://github.com/CartoDB/cartodb-platform/blob/9911ed9c74c4a2cf3521ac29174d6e7faadbf157/cookbooks/cartodb-ci/files/default/CartoDB-DATASERVICES-API-PR-testing.xml#L99). What do you think about passing an environment variable?

**Comment by ethervoid** [comment]
1.- The great value of using Travis is to upgrade/test easily other platform / versions / etc but I this case we use the standard for CARTO and if we make the repository private we should return to Jenkins. In summary, having it already in Jenkins I'll leave as it is

2.- Because we don't provision anything. Chef is used in specific machines to provision but in this case, we are talking about the Jenkins test node. We can use Chef to provision a config file for this tests and so on but IMHO we don't need to test against real Mapbox, we can mockup the response and leave that responsibility to the end-to-end tests.

3. ENV variables are used, most of the time, to pass environment, passwords, users, binary path but not command lines so I'll leave that way

4. Nope, we don't have more test tokens

**Comment by juanignaciosl** [comment]
1.- ok
2.- ok
3.- I'm suggesting passing an api key, which is similar to a password. Chaging [from](https://github.com/CartoDB/cartodb-platform/blob/9911ed9c74c4a2cf3521ac29174d6e7faadbf157/cookbooks/cartodb-ci/files/default/CartoDB-DATASERVICES-API-PR-testing.xml#L99)

```bash
nosetests lib/python/cartodb_services/test
```

to

```bash
MAPBOX_API_KEY=wadus nosetests lib/python/cartodb_services/test
```
4.- As @antoniocarlon mentions, here we have some: https://github.com/CartoDB/cartodb-management/issues/5071#issuecomment-358964218

**Comment by ethervoid** [comment]
3. If we do that we should enable all the provider api keys and change the tests to use real services instead of the mocked ones. Do you find useful use real services in isolated integration tests having end-to-end for that purpose?

4. Oh didn't remember that! Good catch!

**Comment by juanignaciosl** [comment]
After an online talk, we're going to move forward by replacing the hardcoded previous, public api key with an environment variable that must be passed on tests.
