### ISSUE TITLE
Use dataservices with non-master keys

### ISSUE THREAD

**Issue by javitonino** [CartoDB/dataservices-api#518]
It's finally time to talk about the issue with dataservices not being able to be executed with non-master API Keys. It's something that we want to do for the OAuth implementation to be useful. The problem is as follows. SQL API received the API Key and executed the DS service with the matching API Key role. But the API Key is not passed deeper into the stack. Instead, DS matches the role name against some rules to determine the username. This works for the naming of roles in master keys, but not for others.

More discussion: https://github.com/CartoDB/cartodb-management/issues/5191

Objectives:
- A way to use DS without master keys
- Be able to implement permissions. What makes sense here? Maybe the basics (geocoding/isolines/DO)?

**Comment by antoniocarlon** [comment]
The API key data would be like this:
```
{
	"username": "myusername",
	"organization": "",
	"application": "myapplication",
	"permissions": {"dataservices": ["geocoding", "routing", "isolines"]},
	"quotas": {"dataservices": ["geocoding": 100, "isolines": 100]},  <----------- TBD
	"rate_limit": {"dataservices": ["isolines": 5]}  <----------- TBD
}
```

We have several options for the API keys/configuration storage:
**Using `cdb_conf`:**
 - Creating a key `api_keys` to store all the API keys and their permissions:
```
key = api_keys
value = {
	"database_role1": {
		// ...
	}, 
	"database_role2": {
		// ...
	}, 
}
```
The main drawback is that all the API keys would be stored under the same key, and this can be especially problematic for organizations because all the API keys for all the users would be stored here (in a huge JSON)
 - Creating a key `database_role` (maybe with a prefix?) to store the permissions of the API key related to that role:
```
key = database_role
value = // the API key data from above (JSON)
```
The main drawback is that the current organization of `cdb_conf` doesn't seem to favour this approach
**Using a new table:**
Create a new table with the following schema:
```
role | username | organization | application | permissions
```

cc @oleurud  @javitonino @juanignaciosl 

Note: We have already talked about this (using `cdb_conf`), but when we were defining the structure we have found these issues and we would like to discuss it a bit more

**Comment by javitonino** [comment]
> `"organization": ""`

Do we need this? It should be in an entry `cdb_conf` already (since the organization is the same for the whole database).

About the three options:
1. Single key. I would discard it because it makes for slower lookups/updates than the alternatives.
2. Key per role (with prefix?). This looks OK. It's true that it doesn't follow the current design. Also, we access `cdb_conf` though functions and I'm not sure if there is any.
3. New table. Problem is granting the appropriate permissions on the table for all users. Advantage is having a separate schema for this.

2 or 3 look OK to me. 2 is easier to to do, 3 is maybe better (more explicit separation) but a bit more work at the start.

**Comment by juanignaciosl** [comment]
`"permissions": {"dataservices": ["geocoding", "routing", "isolines"]},`

I'd do a flat array. The `dataservices` division is not actually needed nor makes sense from an API point of view, I think. Proposal: `"permissions": ["geocoding", "routing", "isolines"],`.

I agree with @javitonino , `organization` is not needed.

Options:
1.- In a "normal table" it'd be the best alternative, because with index it'd be fast. With the `cdb_conf` limitations in order to take advantage of it we'd need an explicit function that leveraged an index in the first level of the JSON. Probably dismissed.
2.- "The current design" is having a configuration for something under a single key. Option 1 was not bad. This _feels_ really ugly. But, as long as the key is known by the caller (as it should be), you can use [`cdb_getconf`](https://github.com/CartoDB/cartodb-postgresql/blob/0c864694b68565c6b6ec7e0214697ac18c31cef6/scripts-available/CDB_Conf.sql#L40).
3.- It's a lot of more work. Keep in mind that it's a table that you must keep safe, so you also need functions and things become tricky. The best thing of this would be that we could implement at DS extension instead of CARTO, but on the other hand that division just resembles _our_ mental model, not actual needs.

I must admit that I don't love any, but I can't come up with anything better. As we're talking about just a few data (thousands of rows, maybe) that will be _always_ accessed by key, I'd go for 2. There's no explicit benefit on 3 right now and it's a lot more of work, as that's something that you'd need to do at extension level. 2 is not a problem and it should be straightforward. We could eventually migrate if needed.

**Comment by oleurud** [comment]
So, let's go with option 2. Closing

**Comment by oleurud** [comment]
> I'd do a flat array. The dataservices division is not actually needed nor makes sense from an API point of view, I think. Proposal: "permissions": ["geocoding", "routing", "isolines"],.

For me, the `dataservices` key offers scalability. I don't think, we are going to have conflicting keys between different services, but it could be and the key is short and easy enough.

> I agree with @javitonino , organization is not needed.

About `organization` and really also about `username`. We have currently a way to get both:
- if company user: `organization` from cdb_conf and `username` from `pg:roles` & `pg_namespace`
- else:  `username` from cdb_conf

So if we make a new way (using the new entry in cdb_conf), we should add a new if/else to use the new way or the current one.We think, the better is to use the current one in order to maintain the process simple.

**Comment by juanignaciosl** [comment]
- An example about my point about `dataservices` nesting: if the geocoding becomes a REST API, I think that the permission shouldn't change, because the API key grants the geocoding feature, but it'd still be under `dataservices` key. IMHO it couples the API key specification to the implementation.
- I don't understand the second point, maybe I'm too tired :sweat_smile: Could you explain what you mean like I'm five, please? :sweat_smile:

**Comment by juanignaciosl** [comment]
After a talk about the need of the need for `username` and/or `organization`, it seems that they're not needed, because they can be obtained from `cdb_conf`.

**Comment by oleurud** [comment]
About the `dataservices` property, you are right, we dont need it

**Comment by oleurud** [comment]
All clear again :sweat_smile: closing!

**Comment by oleurud** [comment]
> if company user: organization from cdb_conf and username from pg:roles & pg_namespace

@javitonino warned us about it: we can extract the username from pg_roles & pg_namespace (if is an organization user) ONLY if the api key is `master` (only a master key role has an entry on pg_namespace).

So finally, we will need to add the `username` in the `cdb_conf`
