### ISSUE TITLE
TomTom Isoline API parameters - Add to Data Services API

### ISSUE THREAD

**Issue by orrholly** [CartoDB/dataservices-api#522]
@jorgesancha @javitonino @stuartlynn @hannahblue @SebastienBu  @mbforr 

We have a client, Instacart, that needs us to add the TomTom routing API parameters, specifically departAt, to our Data Services API. There are other clients that our team is talking to that have the similar requests (e.g. GVA / LEK / Economical Insurance / GSTV).

Is this something that could be prioritized?

**Comment by javitonino** [comment]
cc @juanignaciosl

**Comment by juanignaciosl** [comment]
This is not a problem from a technical point of view. As @andrewbt says, parameters could be optional. This is a problem from a product perspective because we'd be offering an API whose behavior depends on the user contract. If this becomes an actual need we should explain in the documentation something like "this parameter might not be available for your current subscription; if using it throws a XXX error, contact sales" or something similar.

**Comment by andrewbt** [comment]
agree with stuart, +1. I think the abstraction of parameters across providers is more of a disadvantage than an advantage for us.

**Comment by hannahblue** [comment]
@juanignaciosl, I agree with having a disclaimer in the documentation anytime we need to add an optional parameter that isn't consistent across providers.

@stuartlynn and @andrewbt, I understand valuable parameters shouldn't be excluded just because they're not offered by all providers. We just have to be cautious because we have to have the freedom to switch providers depending on our partnership arrangements with limited disruption to users. Something like @juanignaciosl's suggestion should do the trick.


In any case, for this request it doesn't matter because both providers have the parameter (mapbox doesn't, but we're not using their Isolines right now, and they're changing their API anyway).  

@juanignaciosl do you think this is a short enough effort to go to the response team? Or should we scope it and add it to the list of side tasks? Doesn't sound like it's a full Project level effort.

**Comment by javitonino** [comment]
Nothing more to add about the consistency of the API, I agree with Hannah and Nacho that it's important to keep it consistent among providers so we can switch transparently. Dates for traffic is something commonly supported so it should be OK, but we will have to do it in all providers.

About scheduling, I'd push this as a project, even if it's a short one. Since it's not something that can be done in a day (as anything that involves a dataservices deployment) I think it's better server by a small project.

**Comment by juanignaciosl** [comment]
Agree with @javitonino , this is a (small) project, not something for RT. In addition, there will be conventions and so on that we must agree upon. I understand that this kind of decisions might be a disadvantage for some people but I strongly think that this approach is good in the long term.

**Comment by vhamer** [comment]
This issue was moved to CartoDB/product#268
